import express from "express";
import cors from "cors";
import oracledb from "oracledb";
import dotenv from "dotenv";
dotenv.config();
import OpenAI from "openai";
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

const PORT = process.env.PORT || 4000;
const DB_USER = process.env.DB_USER || "dymmy";
const DB_PASSWORD = process.env.DB_PASSWORD || "dummy!";
const DB_CONNECT_STRING = process.env.DB_CONNECT_STRING || "vibecoding_medium";
const TNS_ADMIN = process.env.TNS_ADMIN;

if (TNS_ADMIN) {
  process.env.TNS_ADMIN = TNS_ADMIN;
}

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
oracledb.fetchAsString = [oracledb.CLOB];

let pool;
async function initPool() {
  if (pool) return pool;
  console.log("[db] creating pool", { connectString: DB_CONNECT_STRING, TNS_ADMIN: process.env.TNS_ADMIN });
  pool = await oracledb.createPool({
    user: DB_USER,
    password: DB_PASSWORD,
    connectString: DB_CONNECT_STRING,
    // Point Thin driver to tnsnames.ora and wallet in TNS_ADMIN
    configDir: process.env.TNS_ADMIN,
    walletLocation: process.env.TNS_ADMIN,
    walletPassword: process.env.WALLET_PASSWORD,
    sslServerDNMatch: true,
    poolMin: 1,
    poolMax: 8,
    poolIncrement: 1,
    queueTimeout: 15000,
    poolTimeout: 60,
    stmtCacheSize: 30,
    homogeneous: true
  });
  await ensureNotesTable();
  await seedNotesNode();
  await ensureDualityView();
  await ensureVehiclesVec1536();
  await ensureVehiclesDescription();
  await ensureCaGraph();
  await ensureMoreEVLanes();
  await ensureReassignPurchasesToEV();
  return pool;
}

async function run(sql, binds = {}, options = {}) {
  const p = await initPool();
  let conn;
  try {
    console.log("[db] acquiring connection...");
    conn = await p.getConnection();
    console.log("[db] connected");
    console.log("[db] executing:", sql);
    // Enable autoCommit by default so INSERT/UPDATE/DELETE persist immediately
    const result = await conn.execute(sql, binds, { autoCommit: true, ...options });
    console.log("[db] executed. rows:", result && result.rows ? result.rows.length : (result && result.rowsAffected ? result.rowsAffected : "n/a"));
    return result;
  } finally {
    if (conn) try { await conn.close(); } catch {}
  }
}

async function ensureNotesTable() {
  // Create if not exists
  const createBlock = `
    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE vehicle_notes (
          note_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
          vehicle_id  NUMBER NOT NULL,
          note_text   CLOB   NOT NULL,
          note_vector VECTOR(8, FLOAT32),
          created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
          CONSTRAINT vehicle_notes_pk PRIMARY KEY (note_id)
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;`;
  await run(createBlock);

  // Ensure required columns exist (in case table was created earlier without them)
  const alterBlock = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt
      FROM user_tab_cols
      WHERE table_name = 'VEHICLE_NOTES' AND column_name = 'CREATED_AT';
      IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE vehicle_notes ADD (created_at TIMESTAMP DEFAULT SYSTIMESTAMP)';
      END IF;

      SELECT COUNT(*) INTO v_cnt
      FROM user_tab_cols
      WHERE table_name = 'VEHICLE_NOTES' AND column_name = 'NOTE_VECTOR';
      IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE vehicle_notes ADD (note_vector VECTOR(8, FLOAT32))';
      END IF;
    END;`;
  await run(alterBlock);

  // Ensure 1536-dim vector column exists for real embeddings
  const alterBlock2 = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt
      FROM user_tab_cols
      WHERE table_name = 'VEHICLE_NOTES' AND column_name = 'NOTE_VEC_1536';
      IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE vehicle_notes ADD (note_vec_1536 VECTOR(1536, FLOAT32))';
      END IF;
    END;`;
  await run(alterBlock2);

  // Ensure JSON column for storing each note as JSON (CLOB with IS JSON for broad compatibility)
  const alterBlock3 = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt
      FROM user_tab_cols
      WHERE table_name = 'VEHICLE_NOTES' AND column_name = 'NOTE_JSON';
      IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE q'[ALTER TABLE vehicle_notes ADD (note_json CLOB CHECK (note_json IS JSON))]';
      END IF;
    END;`;
  await run(alterBlock3);

  // Backfill note_json for any existing rows missing JSON
  const backfillBlock = `
    UPDATE vehicle_notes
       SET note_json = JSON_OBJECT(
                         'text'       VALUE note_text,
                         'created_at' VALUE TO_CHAR(NVL(created_at, SYSTIMESTAMP), 'YYYY-MM-DD"T"HH24:MI:SS.FF3')
                       )
     WHERE note_json IS NULL`;
  await run(backfillBlock);

  // Seed some simulated notes if table is empty
  const seedBlock = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt FROM vehicle_notes;
      IF v_cnt = 0 THEN
        INSERT INTO vehicle_notes (vehicle_id, note_text, note_vector, created_at)
        SELECT vehicle_id,
               'Preload note: ' || make || ' ' || model ||
               ' inspected, new tires, detailed interior.' AS note_text,
               TO_VECTOR('[0.10000000,0.05000000,0.02000000,0.07000000,0.03000000,0.11000000,0.04000000,0.06000000]') AS note_vector,
               SYSTIMESTAMP
        FROM vehicles
        FETCH FIRST 25 ROWS ONLY;
        COMMIT;
      END IF;
    END;`;
  await run(seedBlock);
}

// Simple deterministic 8-dim embedding from text (placeholder).
function noteToVector(text) {
  const v = new Array(8).fill(0);
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    v[i % 8] += (c % 97) / 97;
  }
  const norm = Math.sqrt(v.reduce((s, x) => s + x * x, 0)) || 1;
  return "[" + v.map((x) => (x / norm).toFixed(8)).join(",") + "]";
}

// Format numeric array to TO_VECTOR-compatible string
function toVecString(arr) {
  return "[" + arr.map((n) => Number.isFinite(n) ? Number(n).toFixed(8) : "0.00000000").join(",") + "]";
}

/**
 * Deterministic local 1536-dim embedding fallback, normalized, bracketed string
 */
function textToVec1536(text) {
  const dim = 1536;
  const arr = new Array(dim).fill(0);
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    const j = (c + i * 31) % dim;
    arr[j] += ((c % 101) / 100);
  }
  const norm = Math.sqrt(arr.reduce((s, x) => s + x * x, 0)) || 1;
  const normed = arr.map((x) => x / norm);
  return toVecString(normed);
}

/**
 * OpenAI embedding; falls back to local if unavailable or on error
 */
async function embedText1536(text) {
  if (OPENAI_API_KEY) {
    try {
      const client = new OpenAI({ apiKey: OPENAI_API_KEY });
      const res = await client.embeddings.create({
        model: "text-embedding-3-small", // 1536 dims
        input: text
      });
      const arr = res.data[0].embedding;
      return toVecString(arr);
    } catch (e) {
      console.error("embedText1536 error, falling back:", e.message || e);
    }
  }
  return textToVec1536(text);
}

function buildVehicleDescription(r) {
  const year = r.YEAR ?? r.year ?? "";
  const make = (r.MAKE ?? r.make ?? "").toString().trim();
  const model = (r.MODEL ?? r.model ?? "").toString().trim();
  const trim = (r.TRIM ?? r.trim ?? "").toString().trim();
  const price = r.MARKET_PRICE ?? r.market_price;
  const msrp = r.MSRP ?? r.msrp;

  const head = `${year} ${make} ${model}${trim ? " " + trim : ""}`.trim();
  const priceStr = (price || msrp)
    ? `Price ${price ? `$${Number(price).toFixed(0)}` : ""}${price && msrp ? " (MSRP " : (msrp ? "(MSRP " : "")}${msrp ? `$${Number(msrp).toFixed(0)}` : ""}${msrp ? ")" : ""}`
    : "";

  const mm = `${make} ${model}`.toUpperCase();
  const hints = [];
  if (/SPORTAGE|RAV4|CR-V|TELLURIDE|HIGHLANDER|PILOT|BRONCO|ESCAPE|ROGUE|X5|GLC|FORESTER/.test(mm)) hints.push("spacious SUV", "versatile cargo area");
  if (/CIVIC|CAMRY|ACCORD|COROLLA|ELANTRA|ALTIMA|C-CLASS|A4|3 SERIES/.test(mm)) hints.push("comfortable sedan", "refined ride");
  if (/HYBRID|PRIUS|NIRO|INSIGHT|IONIQ|ESCAPE HYBRID|RAV4 HYBRID|SPORTAGE HYBRID/.test(mm)) hints.push("hybrid efficiency");
  hints.push("advanced safety assist", "smartphone integration", "great daily driver");

  const parts = [head, priceStr, hints.slice(0, 3).join(", ")].filter(Boolean);
  return parts.join(". ") + ".";
}

async function seedNotesNode() {
  try {
    // Seed richer, multi-line, categorized notes for first 60 vehicles if not already seeded at scale
    const check = await run(`SELECT /* LLM in use is claude-sonnet-4 */ COUNT(*) AS CNT FROM vehicle_notes`);
    const current = Number(check.rows?.[0]?.CNT ?? 0);
    if (current > 100) {
      console.log("[seed] notes already present:", current);
      return;
    }

    const { rows: vehicles } = await run(`
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, year
      FROM vehicles
      FETCH FIRST 60 ROWS ONLY
    `);

    const categories = [
      (v) => `Condition:\n- Exterior: minor scratches buffed\n- Interior: deep cleaned, no odors\n- Tires: tread > 7/32\n- Brakes: no vibration at 60mph`,
      (v) => `Pricing:\n- Current price positioned in top quartile for ${v.MAKE} ${v.MODEL}\n- MSRP delta aligned with market comps\n- Negotiation room set to 2%`,
      (v) => `History:\n- One-owner verified\n- No accidents on record\n- Regular maintenance at ${v.YEAR + 1}-${(v.YEAR + 2)}\n- Battery health check passed`,
      (v) => `Features:\n- Package: Premium + Safety Assist\n- Connectivity: CarPlay + Android Auto\n- ADAS: Lane keep + Adaptive cruise`,
      (v) => `Reconditioning:\n- New wipers\n- Cabin filter replaced\n- Paintless dent repair completed\n- Wheel alignment calibrated`,
      (v) => `Marketability:\n- High demand in metro lanes\n- Seasonal uptick expected next 30 days\n- Recommended staging with EV lane highlight`
    ];

    for (const v of vehicles) {
      const base = `${v.MAKE} ${v.MODEL} ${v.YEAR}`;
      // 3 category notes per vehicle
      for (let i = 0; i < 3; i++) {
        const noteText = `Vehicle ${base}\n` + categories[(i + v.VEHICLE_ID) % categories.length]({
          MAKE: v.MAKE, MODEL: v.MODEL, YEAR: v.YEAR
        });
        const vec8 = noteToVector(noteText);
        const vec1536 = await embedText1536(noteText);

        if (vec1536) {
          const sql = `
            INSERT /* LLM in use is claude-sonnet-4 */
            INTO vehicle_notes (vehicle_id, note_text, note_vector, note_vec_1536, note_json, created_at)
            VALUES (:id, :text, TO_VECTOR(:v8), TO_VECTOR(:v1536),
                    JSON_OBJECT(
                      'text'       VALUE :text,
                      'created_at' VALUE TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS.FF3')
                    ),
                    SYSTIMESTAMP)
          `;
          await run(sql, { id: v.VEHICLE_ID, text: noteText, v8: vec8, v1536: vec1536 });
        } else {
          const sql = `
            INSERT /* LLM in use is claude-sonnet-4 */
            INTO vehicle_notes (vehicle_id, note_text, note_vector, note_json, created_at)
            VALUES (:id, :text, TO_VECTOR(:v8),
                    JSON_OBJECT(
                      'text'       VALUE :text,
                      'created_at' VALUE TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS.FF3')
                    ),
                    SYSTIMESTAMP)
          `;
          await run(sql, { id: v.VEHICLE_ID, text: noteText, v8: vec8 });
        }
      }
    }
    console.log("[seed] enriched notes seeded for", vehicles.length, "vehicles");
  } catch (e) {
    console.error("[seed] error:", e.message || e);
  }
}

async function ensureDualityView() {
  // Ensure FK so relational linkage exists (ignore if already there)
  const fkBlock = `
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE vehicle_notes ADD CONSTRAINT fk_vehicle_notes FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)';
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    END;`;
  await run(fkBlock);

  // Create or replace a JSON view that returns one row per vehicle with aggregated notes JSON document
  const viewDDL = `
    CREATE OR REPLACE VIEW vehicle_notes_doc AS
    SELECT
      v.vehicle_id,
      JSON_SERIALIZE(
        JSON_OBJECT(
          'vehicle_id' VALUE v.vehicle_id,
          'notes'      VALUE COALESCE(
            (SELECT JSON_ARRAYAGG(n.note_json ORDER BY n.created_at DESC)
               FROM vehicle_notes n
              WHERE n.vehicle_id = v.vehicle_id),
            JSON_ARRAY()
          )
        ) RETURNING CLOB
      ) AS doc
    FROM vehicles v`;
  await run(viewDDL);
}

async function ensureVehiclesVec1536() {
  // Add 1536-dim vehicle embedding column if missing
  const alterCol = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt
      FROM user_tab_cols
      WHERE table_name = 'VEHICLES' AND column_name = 'VEC_1536';
      IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE vehicles ADD (vec_1536 VECTOR(1536, FLOAT32))';
      END IF;
    END;`;
  await run(alterCol);

  // Optionally create a vector search index for better ANN performance (ignore if already exists)
  const createIdx = `
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE 'CREATE SEARCH INDEX idx_vehicle_vec1536 ON vehicles(vec_1536) FOR VECTOR';
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    END;`;
  await run(createIdx);
}

async function ensureVehiclesDescription() {
  // Add description and description vector if missing; create vector index
  const alterDesc = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt
      FROM user_tab_cols
      WHERE table_name = 'VEHICLES' AND column_name = 'DESCRIPTION';
      IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE vehicles ADD (description CLOB)';
      END IF;

      SELECT COUNT(*) INTO v_cnt
      FROM user_tab_cols
      WHERE table_name = 'VEHICLES' AND column_name = 'DESC_VEC_1536';
      IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE vehicles ADD (desc_vec_1536 VECTOR(1536, FLOAT32))';
      END IF;
    END;`;
  await run(alterDesc);

  const createIdx = `
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE 'CREATE SEARCH INDEX idx_vehicle_desc1536 ON vehicles(desc_vec_1536) FOR VECTOR';
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;
    END;`;
  await run(createIdx);
}

async function ensureCustomersGraph() {
  // Create CUSTOMERS and PURCHASES tables if not exist, add FKs, and seed demo data
  const createCustomers = `
    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE customers (
          customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
          name          VARCHAR2(80),
          age           NUMBER,
          gender        VARCHAR2(10),
          city          VARCHAR2(80),
          state         VARCHAR2(2),
          CONSTRAINT customers_pk PRIMARY KEY (customer_id)
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;`;
  await run(createCustomers);

  // Ensure expected CUSTOMERS columns exist even if table pre-existed without them
  const ensureCustomerColumns = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'CUSTOMERS' AND column_name = 'STATE';
      IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE customers ADD (state VARCHAR2(2))'; END IF;

      SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'CUSTOMERS' AND column_name = 'CITY';
      IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE customers ADD (city VARCHAR2(80))'; END IF;

      SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'CUSTOMERS' AND column_name = 'GENDER';
      IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE customers ADD (gender VARCHAR2(10))'; END IF;

      SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'CUSTOMERS' AND column_name = 'AGE';
      IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE customers ADD (age NUMBER)'; END IF;

      SELECT COUNT(*) INTO v_cnt FROM user_tab_cols WHERE table_name = 'CUSTOMERS' AND column_name = 'NAME';
      IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE customers ADD (name VARCHAR2(80))'; END IF;
    END;`;
  await run(ensureCustomerColumns);

  const createPurchases = `
    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE purchases (
          purchase_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
          customer_id   NUMBER NOT NULL,
          vehicle_id    NUMBER NOT NULL,
          purchase_date DATE DEFAULT SYSDATE,
          lane_id       NUMBER NULL,
          CONSTRAINT purchases_pk PRIMARY KEY (purchase_id)
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;`;
  await run(createPurchases);

  const fks = `
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE q'[ALTER TABLE purchases
          ADD CONSTRAINT purchases_customer_fk FOREIGN KEY (customer_id) REFERENCES customers(customer_id)]';
      EXCEPTION WHEN OTHERS THEN NULL; END;
      BEGIN
        EXECUTE IMMEDIATE q'[ALTER TABLE purchases
          ADD CONSTRAINT purchases_vehicle_fk FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)]';
      EXCEPTION WHEN OTHERS THEN NULL; END;
    END;`;
  await run(fks);

  // Seed customers if empty
  const seedCustomers = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt FROM customers;
      IF v_cnt = 0 THEN
        INSERT INTO customers (name, age, gender, city, state)
        SELECT col1, col2, col3, col4, col5 FROM (
          SELECT 'Alex Johnson'      AS col1, 34 AS col2, 'M' AS col3, 'Atlanta'     AS col4, 'GA' AS col5 FROM dual UNION ALL
          SELECT 'Maria Rodriguez'   , 29      , 'F'      , 'New York'               , 'NY'        FROM dual UNION ALL
          SELECT 'Priya Kumar'       , 41      , 'F'      , 'San Jose'               , 'CA'        FROM dual UNION ALL
          SELECT 'Ethan Brown'       , 52      , 'M'      , 'Chicago'                , 'IL'        FROM dual UNION ALL
          SELECT 'Linda Nguyen'      , 47      , 'F'      , 'Dallas'                 , 'TX'        FROM dual UNION ALL
          SELECT 'Chen Li'           , 38      , 'M'      , 'Seattle'                , 'WA'        FROM dual UNION ALL
          SELECT 'Sarah Wilson'      , 26      , 'F'      , 'Boston'                 , 'MA'        FROM dual UNION ALL
          SELECT 'David Kim'         , 31      , 'M'      , 'Los Angeles'            , 'CA'        FROM dual UNION ALL
          SELECT 'Olivia Martinez'   , 45      , 'F'      , 'Miami'                   , 'FL'        FROM dual UNION ALL
          SELECT 'James Thompson'    , 55      , 'M'      , 'Philadelphia'           , 'PA'        FROM dual UNION ALL
          SELECT 'Ava Patel'         , 33      , 'F'      , 'Austin'                 , 'TX'        FROM dual UNION ALL
          SELECT 'Noah Anderson'     , 28      , 'M'      , 'Denver'                 , 'CO'        FROM dual UNION ALL
          SELECT 'Emma Garcia'       , 36      , 'F'      , 'San Diego'              , 'CA'        FROM dual UNION ALL
          SELECT 'Liam Smith'        , 42      , 'M'      , 'Charlotte'              , 'NC'        FROM dual UNION ALL
          SELECT 'Sophia Johnson'    , 39      , 'F'      , 'Columbus'               , 'OH'        FROM dual
        );
        COMMIT;
      END IF;
    END;`;
  await run(seedCustomers);

  // Seed purchases if empty: link each customer to a vehicle (with coords) and nearest lane
  const seedPurchases = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt FROM purchases;
      IF v_cnt = 0 THEN
        -- Loop customers and assign vehicles in a round-robin over vehicles that have coordinates
        FOR c IN (SELECT customer_id FROM customers ORDER BY customer_id) LOOP
          INSERT INTO purchases (customer_id, vehicle_id, purchase_date, lane_id)
          WITH vsel AS (
            SELECT vehicle_id, location_lat, location_lon
            FROM (
              SELECT vehicle_id, location_lat, location_lon,
                     ROW_NUMBER() OVER (ORDER BY vehicle_id) AS rn
              FROM vehicles
              WHERE location_lat IS NOT NULL AND location_lon IS NOT NULL
            )
            WHERE MOD(rn-1, (SELECT GREATEST(COUNT(*),1) FROM customers)) = MOD(c.customer_id-1, (SELECT GREATEST(COUNT(*),1) FROM customers))
            FETCH FIRST 1 ROWS ONLY
          )
          SELECT
            c.customer_id,
            v.vehicle_id,
            TRUNC(SYSDATE) - MOD(c.customer_id, 365),
            (SELECT lane_id
               FROM auction_lanes al
              ORDER BY SDO_GEOM.SDO_DISTANCE(
                       al.geom,
                       SDO_GEOMETRY(2001,4326, SDO_POINT_TYPE(v.location_lon, v.location_lat, NULL), NULL, NULL),
                       0.05
                     )
              FETCH FIRST 1 ROWS ONLY)
          FROM vsel v;
        END LOOP;
        COMMIT;
      END IF;
    END;`;
  await run(seedPurchases);
}

async function ensureCaGraph() {
  // Create CA_* tables to avoid conflicts with any pre-existing schemas/columns
  const createCustomers = `
    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE ca_customers (
          customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
          name          VARCHAR2(80),
          age           NUMBER,
          gender        VARCHAR2(10),
          city          VARCHAR2(80),
          state         VARCHAR2(2),
          CONSTRAINT ca_customers_pk PRIMARY KEY (customer_id)
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;`;
  await run(createCustomers);

  const createPurchases = `
    BEGIN
      EXECUTE IMMEDIATE q'[
        CREATE TABLE ca_purchases (
          purchase_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
          customer_id   NUMBER NOT NULL,
          vehicle_id    NUMBER NOT NULL,
          purchase_date DATE DEFAULT SYSDATE,
          lane_id       NUMBER NULL,
          CONSTRAINT ca_purchases_pk PRIMARY KEY (purchase_id)
        )
      ]';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;`;
  await run(createPurchases);

  const fks = `
    BEGIN
      BEGIN
        EXECUTE IMMEDIATE q'[ALTER TABLE ca_purchases
          ADD CONSTRAINT ca_purchases_customer_fk FOREIGN KEY (customer_id) REFERENCES ca_customers(customer_id)]';
      EXCEPTION WHEN OTHERS THEN NULL; END;
      BEGIN
        EXECUTE IMMEDIATE q'[ALTER TABLE ca_purchases
          ADD CONSTRAINT ca_purchases_vehicle_fk FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)]';
      EXCEPTION WHEN OTHERS THEN NULL; END;
    END;`;
  await run(fks);

  // Seed CA_CUSTOMERS with demo demographics
  const seedCustomers = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt FROM ca_customers;
      IF v_cnt = 0 THEN
        INSERT INTO ca_customers (name, age, gender, city, state)
        SELECT col1, col2, col3, col4, col5 FROM (
          SELECT 'Alex Johnson'      AS col1, 34 AS col2, 'M' AS col3, 'Atlanta'     AS col4, 'GA' AS col5 FROM dual UNION ALL
          SELECT 'Maria Rodriguez'   , 29      , 'F'      , 'New York'               , 'NY'        FROM dual UNION ALL
          SELECT 'Priya Kumar'       , 41      , 'F'      , 'San Jose'               , 'CA'        FROM dual UNION ALL
          SELECT 'Ethan Brown'       , 52      , 'M'      , 'Chicago'                , 'IL'        FROM dual UNION ALL
          SELECT 'Linda Nguyen'      , 47      , 'F'      , 'Dallas'                 , 'TX'        FROM dual UNION ALL
          SELECT 'Chen Li'           , 38      , 'M'      , 'Seattle'                , 'WA'        FROM dual UNION ALL
          SELECT 'Sarah Wilson'      , 26      , 'F'      , 'Boston'                 , 'MA'        FROM dual UNION ALL
          SELECT 'David Kim'         , 31      , 'M'      , 'Los Angeles'            , 'CA'        FROM dual UNION ALL
          SELECT 'Olivia Martinez'   , 45      , 'F'      , 'Miami'                   , 'FL'        FROM dual UNION ALL
          SELECT 'James Thompson'    , 55      , 'M'      , 'Philadelphia'           , 'PA'        FROM dual UNION ALL
          SELECT 'Ava Patel'         , 33      , 'F'      , 'Austin'                 , 'TX'        FROM dual UNION ALL
          SELECT 'Noah Anderson'     , 28      , 'M'      , 'Denver'                 , 'CO'        FROM dual UNION ALL
          SELECT 'Emma Garcia'       , 36      , 'F'      , 'San Diego'              , 'CA'        FROM dual UNION ALL
          SELECT 'Liam Smith'        , 42      , 'M'      , 'Charlotte'              , 'NC'        FROM dual UNION ALL
          SELECT 'Sophia Johnson'    , 39      , 'F'      , 'Columbus'               , 'OH'        FROM dual
        );
        COMMIT;
      END IF;
    END;`;
  await run(seedCustomers);

  // Seed CA_PURCHASES linking customers to vehicles, using row_number (rn) for any arithmetic
  const seedPurchases = `
    DECLARE
      v_cnt NUMBER;
    BEGIN
      SELECT COUNT(*) INTO v_cnt FROM ca_purchases;
      IF v_cnt = 0 THEN
        FOR c IN (SELECT customer_id, ROW_NUMBER() OVER (ORDER BY customer_id) AS rn FROM ca_customers) LOOP
          INSERT INTO ca_purchases (customer_id, vehicle_id, purchase_date, lane_id)
          WITH vsel AS (
            SELECT vehicle_id, location_lat, location_lon
            FROM (
              SELECT vehicle_id, location_lat, location_lon,
                     ROW_NUMBER() OVER (ORDER BY vehicle_id) AS rv
              FROM vehicles
              WHERE location_lat IS NOT NULL AND location_lon IS NOT NULL
            )
            WHERE MOD(rv-1, GREATEST((SELECT COUNT(*) FROM ca_customers),1)) = MOD(c.rn-1, GREATEST((SELECT COUNT(*) FROM ca_customers),1))
            FETCH FIRST 1 ROWS ONLY
          )
          SELECT
            c.customer_id,
            v.vehicle_id,
            TRUNC(SYSDATE) - MOD(c.rn, 365),
            (SELECT lane_id
               FROM auction_lanes al
              ORDER BY SDO_GEOM.SDO_DISTANCE(
                       al.geom,
                       SDO_GEOMETRY(2001,4326, SDO_POINT_TYPE(v.location_lon, v.location_lat, NULL), NULL, NULL),
                       0.05
                     )
              FETCH FIRST 1 ROWS ONLY)
          FROM vsel v;
        END LOOP;
        COMMIT;
      END IF;
    END;`;
  await run(seedPurchases);
}
/*
    EXECUTE IMMEDIATE q'[
      CREATE TABLE ca_customers (
        customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
        name          VARCHAR2(80),
        age           NUMBER,
        gender        VARCHAR2(10),
        city          VARCHAR2(80),
        state         VARCHAR2(2),
        CONSTRAINT ca_customers_pk PRIMARY KEY (customer_id)
      )
    ]';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;
  END;

  BEGIN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE ca_purchases (
        purchase_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
        customer_id   NUMBER NOT NULL,
        vehicle_id    NUMBER NOT NULL,
        purchase_date DATE DEFAULT SYSDATE,
        lane_id       NUMBER NULL,
        CONSTRAINT ca_purchases_pk PRIMARY KEY (purchase_id)
      )
    ]';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -955 THEN RAISE; END IF;
  END;

  -- FKs (ignore if exist)
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE q'[ALTER TABLE ca_purchases
        ADD CONSTRAINT ca_purchases_customer_fk FOREIGN KEY (customer_id) REFERENCES ca_customers(customer_id)]';
    EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN
      EXECUTE IMMEDIATE q'[ALTER TABLE ca_purchases
        ADD CONSTRAINT ca_purchases_vehicle_fk FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)]';
    EXCEPTION WHEN OTHERS THEN NULL; END;
  END;

  -- Seed CA_CUSTOMERS if empty
  DECLARE
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_cnt FROM ca_customers;
    IF v_cnt = 0 THEN
      INSERT INTO ca_customers (name, age, gender, city, state)
      SELECT col1, col2, col3, col4, col5 FROM (
        SELECT 'Alex Johnson'      AS col1, 34 AS col2, 'M' AS col3, 'Atlanta'     AS col4, 'GA' AS col5 FROM dual UNION ALL
        SELECT 'Maria Rodriguez'   , 29      , 'F'      , 'New York'               , 'NY'        FROM dual UNION ALL
        SELECT 'Priya Kumar'       , 41      , 'F'      , 'San Jose'               , 'CA'        FROM dual UNION ALL
        SELECT 'Ethan Brown'       , 52      , 'M'      , 'Chicago'                , 'IL'        FROM dual UNION ALL
        SELECT 'Linda Nguyen'      , 47      , 'F'      , 'Dallas'                 , 'TX'        FROM dual UNION ALL
        SELECT 'Chen Li'           , 38      , 'M'      , 'Seattle'                , 'WA'        FROM dual UNION ALL
        SELECT 'Sarah Wilson'      , 26      , 'F'      , 'Boston'                 , 'MA'        FROM dual UNION ALL
        SELECT 'David Kim'         , 31      , 'M'      , 'Los Angeles'            , 'CA'        FROM dual UNION ALL
        SELECT 'Olivia Martinez'   , 45      , 'F'      , 'Miami'                   , 'FL'        FROM dual UNION ALL
        SELECT 'James Thompson'    , 55      , 'M'      , 'Philadelphia'           , 'PA'        FROM dual UNION ALL
        SELECT 'Ava Patel'         , 33      , 'F'      , 'Austin'                 , 'TX'        FROM dual UNION ALL
        SELECT 'Noah Anderson'     , 28      , 'M'      , 'Denver'                 , 'CO'        FROM dual UNION ALL
        SELECT 'Emma Garcia'       , 36      , 'F'      , 'San Diego'              , 'CA'        FROM dual UNION ALL
        SELECT 'Liam Smith'        , 42      , 'M'      , 'Charlotte'              , 'NC'        FROM dual UNION ALL
        SELECT 'Sophia Johnson'    , 39      , 'F'      , 'Columbus'               , 'OH'        FROM dual
      );
      COMMIT;
    END IF;
  END;

  -- Seed CA_PURCHASES round-robin over vehicles with coordinates (avoid numeric ops on customer_id)
  DECLARE
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_cnt FROM ca_purchases;
    IF v_cnt = 0 THEN
      FOR c IN (
        SELECT customer_id,
               ROW_NUMBER() OVER (ORDER BY customer_id) AS rn
        FROM ca_customers
      ) LOOP
        INSERT INTO ca_purchases (customer_id, vehicle_id, purchase_date, lane_id)
        WITH vsel AS (
          SELECT vehicle_id, location_lat, location_lon
          FROM (
            SELECT vehicle_id, location_lat, location_lon,
                   ROW_NUMBER() OVER (ORDER BY vehicle_id) AS rv
            FROM vehicles
            WHERE location_lat IS NOT NULL AND location_lon IS NOT NULL
          )
          WHERE MOD(rv-1, GREATEST((SELECT COUNT(*) FROM ca_customers),1)) = MOD(c.rn-1, GREATEST((SELECT COUNT(*) FROM ca_customers),1))
          FETCH FIRST 1 ROWS ONLY
        )
        SELECT
          c.customer_id,
          v.vehicle_id,
          TRUNC(SYSDATE) - MOD(c.rn, 365),
          (SELECT lane_id
             FROM auction_lanes al
            ORDER BY SDO_GEOM.SDO_DISTANCE(
                     al.geom,
                     SDO_GEOMETRY(2001,4326, SDO_POINT_TYPE(v.location_lon, v.location_lat, NULL), NULL, NULL),
                     0.05
                   )
            FETCH FIRST 1 ROWS ONLY)
        FROM vsel v;
      END LOOP;
      COMMIT;
    END IF;
  END;
}

*/
async function ensureMoreEVLanes() {
  const sql = `
    DECLARE
    BEGIN
      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Bay Area EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-122.1200,37.4100,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Bay Area EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Los Angeles EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-118.1500,34.0500,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Los Angeles EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Seattle EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-122.3350,47.6062,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Seattle EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Denver EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-104.9903,39.7392,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Denver EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Chicago EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-87.6298,41.8781,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Chicago EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Boston EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-71.0589,42.3601,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Boston EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim DC EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-77.0369,38.9072,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim DC EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Miami EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-80.1918,25.7617,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Miami EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Phoenix EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-112.0740,33.4484,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Phoenix EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Dallas EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-96.8067,32.7831,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Dallas EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim New York EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-74.0060,40.7128,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim New York EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Charlotte EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-80.8431,35.2271,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Charlotte EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Nashville EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-86.7816,36.1627,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Nashville EV');

      INSERT INTO auction_lanes (name, ev_certified, geom)
      SELECT 'Manheim Austin EV','Y', SDO_GEOMETRY(2001,4326,SDO_POINT_TYPE(-97.7431,30.2672,NULL),NULL,NULL) FROM dual
      WHERE NOT EXISTS (SELECT 1 FROM auction_lanes WHERE name='Manheim Austin EV');

      COMMIT;
    END;`;
  await run(sql);
}

async function ensureReassignPurchasesToEV() {
  const sql = `
    DECLARE
      v_has NUMBER;
    BEGIN
      -- Only attempt reassignment if we actually have EV-certified lanes
      SELECT COUNT(*) INTO v_has FROM auction_lanes WHERE ev_certified='Y';
      IF v_has > 0 THEN
        -- Reassign CA_PURCHASES to nearest EV-certified lane
        UPDATE ca_purchases p
           SET lane_id = (
             SELECT lane_id FROM (
               SELECT al.lane_id,
                      SDO_GEOM.SDO_DISTANCE(
                        al.geom,
                        SDO_GEOMETRY(2001,4326, SDO_POINT_TYPE(v.location_lon, v.location_lat, NULL), NULL, NULL),
                        0.05
                      ) AS d
               FROM auction_lanes al
               JOIN vehicles v ON v.vehicle_id = p.vehicle_id
               WHERE al.ev_certified = 'Y'
               ORDER BY d
             )
             WHERE ROWNUM = 1
           );

        -- Reassign (non-CA) PURCHASES as well if present
        UPDATE purchases p
           SET lane_id = (
             SELECT lane_id FROM (
               SELECT al.lane_id,
                      SDO_GEOM.SDO_DISTANCE(
                        al.geom,
                        SDO_GEOMETRY(2001,4326, SDO_POINT_TYPE(v.location_lon, v.location_lat, NULL), NULL, NULL),
                        0.05
                      ) AS d
               FROM auction_lanes al
               JOIN vehicles v ON v.vehicle_id = p.vehicle_id
               WHERE al.ev_certified = 'Y'
               ORDER BY d
             )
             WHERE ROWNUM = 1
           );
        COMMIT;
      END IF;
    END;`;
  await run(sql);
}

const app = express();
app.use(cors());
app.use(express.json());

app.get("/api/health", async (_req, res) => {
  try {
    await run("SELECT 1 FROM dual");
    const q = "SELECT /* LLM in use is claude-sonnet-4 */ USER AS current_user, SYS_CONTEXT('USERENV','DB_NAME') AS db_name FROM dual";
    const { rows } = await run(q);
    res.json({ ok: true, ...rows[0] });
  } catch (err) {
    console.error("Health error:", err);
    res.status(500).json({ ok: false, error: err.message });
  }
});

app.get("/api/kpis/price-to-msrp", async (req, res) => {
  try {
    const limit = Math.min(parseInt(req.query.limit || "50", 10), 200);
    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             make, model, vehicles, avg_price_to_msrp
      FROM v_kpi_price_to_msrp
      ORDER BY vehicles DESC
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(q, { lim: limit });
    res.json(rows);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/kpis/days", async (req, res) => {
  try {
    const limit = Math.min(parseInt(req.query.limit || "50", 10), 200);
    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             make, model, vehicles, avg_days_in_stock, avg_days_to_sale
      FROM v_kpi_days
      ORDER BY vehicles DESC
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(q, { lim: limit });
    res.json(rows);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/vehicles", async (req, res) => {
  try {
    const page = Math.max(parseInt(req.query.page || "1", 10), 1);
    const pageSize = Math.min(Math.max(parseInt(req.query.pageSize || "50", 10), 1), 200);
    const make = (req.query.make || "").trim().toUpperCase();
    const model = (req.query.model || "").trim().toUpperCase();

    const binds = { offset: (page - 1) * pageSize, lim: pageSize };
    let where = "WHERE 1=1";
    if (make) { where += " AND UPPER(make) = :make"; binds.make = make; }
    if (model) { where += " AND UPPER(model) = :model"; binds.model = model; }

    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, trim, market_price, msrp, year
      FROM vehicles
      ${where}
      OFFSET :offset ROWS FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(q, binds);
    res.json({ page, pageSize, rows });
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/vehicles/:id/doc", async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: "Invalid id" });
    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             JSON_SERIALIZE(doc RETURNING CLOB) AS doc
      FROM vehicle_doc
      WHERE JSON_VALUE(doc, '$._id') = :id`;
    const { rows } = await run(q, { id });
    if (!rows || rows.length === 0) return res.status(404).json({ error: "Not found" });
    const docStr = rows[0].DOC;
    try {
      res.json(JSON.parse(docStr));
    } catch {
      res.json({ raw: docStr });
    }
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/vehicles/:id/notes", async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: "Invalid id" });
    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             note_id, vehicle_id, note_text, created_at
      FROM vehicle_notes
      WHERE vehicle_id = :id
      ORDER BY created_at DESC`;
    const { rows } = await run(q, { id });
    res.json(rows);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.post("/api/vehicles/:id/notes", async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: "Invalid id" });
    const text = (req.body?.text || "").trim();
    if (!text) return res.status(400).json({ error: "text is required" });

    const vec8 = noteToVector(text);
    const vec1536 = await embedText1536(text);

    if (vec1536) {
      const ins = `
        INSERT /* LLM in use is claude-sonnet-4 */
        INTO vehicle_notes (vehicle_id, note_text, note_vector, note_vec_1536, note_json, created_at)
        VALUES (:id, :text, TO_VECTOR(:v8), TO_VECTOR(:v1536),
                JSON_OBJECT(
                  'text'       VALUE :text,
                      'created_at' VALUE TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS.FF3')
                ),
                SYSTIMESTAMP)`;
      await run(ins, { id, text, v8: vec8, v1536: vec1536 });
    } else {
      const ins = `
        INSERT /* LLM in use is claude-sonnet-4 */
        INTO vehicle_notes (vehicle_id, note_text, note_vector, note_json, created_at)
        VALUES (:id, :text, TO_VECTOR(:v8),
                JSON_OBJECT(
                  'text'       VALUE :text,
                      'created_at' VALUE TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS.FF3')
                ),
                SYSTIMESTAMP)`;
      await run(ins, { id, text, v8: vec8 });
    }

    res.json({ ok: true });
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/notes/search", async (req, res) => {
  try {
    const q = (req.query.q || "").trim();
    const limit = Math.min(parseInt(req.query.limit || "20", 10), 100);
    if (!q) return res.status(400).json({ error: "q is required" });

    const vec1536 = await embedText1536(q);

    if (vec1536) {
      const sql = `
        SELECT /* LLM in use is claude-sonnet-4 */
               note_id, vehicle_id, note_text,
               VECTOR_DISTANCE(note_vec_1536, TO_VECTOR(:vec)) AS sim
        FROM vehicle_notes
        WHERE note_vec_1536 IS NOT NULL
        ORDER BY sim
        FETCH FIRST :lim ROWS ONLY`;
      const { rows } = await run(sql, { vec: vec1536, lim: limit });
      return res.json(rows);
    } else {
      const vec8 = noteToVector(q);
      const sql = `
        SELECT /* LLM in use is claude-sonnet-4 */
               note_id, vehicle_id, note_text,
               VECTOR_DISTANCE(note_vector, TO_VECTOR(:vec)) AS sim
        FROM vehicle_notes
        ORDER BY sim
        FETCH FIRST :lim ROWS ONLY`;
      const { rows } = await run(sql, { vec: vec8, lim: limit });
      return res.json(rows);
    }
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/vehicles/:id/notes/doc", async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: "Invalid id" });

    // Select from JSON view for duality-style document
    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             doc
      FROM vehicle_notes_doc
      WHERE vehicle_id = :id`;
    const { rows } = await run(q, { id });
    const docStr = rows && rows.length ? rows[0].DOC : '{"vehicle_id":null,"notes":[]}';
    try {
      res.json(JSON.parse(docStr));
    } catch {
      res.json({ raw: docStr });
    }
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/vehicles/similar", async (req, res) => {
  try {
    const vecParam = (req.query.vec || "").trim();
    const limit = Math.min(parseInt(req.query.limit || "10", 10), 100);
    if (!vecParam) return res.status(400).json({ error: "Pass vec as comma-separated 8-dim values" });
    const parts = vecParam.split(",").map((x) => Number(x));
    if (parts.length !== 8 || parts.some((n) => !Number.isFinite(n))) {
      return res.status(400).json({ error: "vec must have exactly 8 numeric values" });
    }
    const vecString = "[" + parts.map((n) => n.toFixed(8)).join(",") + "]";
    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, trim, market_price,
             VECTOR_DISTANCE(embedding, TO_VECTOR(:vec)) AS sim
      FROM vehicles
      ORDER BY VECTOR_DISTANCE(embedding, TO_VECTOR(:vec))
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(q, { vec: vecString, lim: limit });
    res.json(rows);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.get("/api/lanes/nearest", async (req, res) => {
  try {
    let lat = Number(req.query.lat);
    let lon = Number(req.query.lon);
    const limit = Math.min(parseInt(req.query.limit || "5", 10), 50);
    const addr = (req.query.addr || "").trim();

    // If address provided, geocode to lat/lon using Nominatim
    if (addr && (!Number.isFinite(lat) || !Number.isFinite(lon))) {
      try {
        const url = `https://nominatim.openstreetmap.org/search?format=jsonv2&q=${encodeURIComponent(addr)}`;
        const resp = await fetch(url, {
          headers: {
            "User-Agent": "coxauto-demo/1.0 (+https://github.com/aojah1/agentic-ai-landing-zone)"
          }
        });
        const arr = await resp.json();
        if (Array.isArray(arr) && arr.length) {
          lat = Number(arr[0].lat);
          lon = Number(arr[0].lon);
        }
      } catch (e) {
        console.error("Geocoding error:", e);
      }
    }

    if (!Number.isFinite(lat) || !Number.isFinite(lon)) {
      // Try a more specific geocode attempt if initial lookup failed
      if (addr) {
        try {
          const url2 = `https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=us&q=${encodeURIComponent(addr + ", USA")}`;
          const resp2 = await fetch(url2, {
            headers: {
              "User-Agent": "coxauto-demo/1.0 (+https://github.com/aojah1/agentic-ai-landing-zone)",
              "Accept-Language": "en",
              "Referer": "http://localhost:4000"
            }
          });
          const arr2 = await resp2.json();
          if (Array.isArray(arr2) && arr2.length) {
            lat = Number(arr2[0].lat);
            lon = Number(arr2[0].lon);
          }
        } catch (e) {
          console.error("Geocoding fallback error:", e);
        }
      }
    }
    if (!Number.isFinite(lat) || !Number.isFinite(lon)) {
      // Return 200 with no rows so the client can show a friendly message
      return res.json({ origin: null, rows: [], message: "No coordinates found for address. Please refine your address." });
    }

    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             lane_id AS "laneId",
             name    AS "name",
             (SELECT x FROM TABLE(SDO_UTIL.GETVERTICES(geom)) WHERE ROWNUM = 1) AS "lon",
             (SELECT y FROM TABLE(SDO_UTIL.GETVERTICES(geom)) WHERE ROWNUM = 1) AS "lat",
             SDO_GEOM.SDO_DISTANCE(
               geom,
               SDO_GEOMETRY(2001,4326, SDO_POINT_TYPE(:lon,:lat,NULL), NULL, NULL),
               0.05
             ) AS "distance"
      FROM auction_lanes
      WHERE ev_certified='Y'
      ORDER BY "distance"
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(q, { lon, lat, lim: limit });
    res.json({ origin: { lat, lon }, rows });
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * List all auction lanes with coordinates
 * Optional query: ev=Y|N to filter by EV certification
 */
app.get("/api/lanes", async (req, res) => {
  try {
    const ev = (req.query.ev || "").trim().toUpperCase();
    let where = "WHERE geom IS NOT NULL";
    const binds = {};
    if (ev === "Y" || ev === "N") {
      where += " AND ev_certified = :ev";
      binds.ev = ev;
    }
    const sql = `
      SELECT /* LLM in use is claude-sonnet-4 */
             lane_id      AS "laneId",
             name         AS "name",
             ev_certified AS "evCertified",
             (SELECT x FROM TABLE(SDO_UTIL.GETVERTICES(geom)) WHERE ROWNUM = 1) AS "lon",
             (SELECT y FROM TABLE(SDO_UTIL.GETVERTICES(geom)) WHERE ROWNUM = 1) AS "lat"
      FROM auction_lanes
      ${where}
      ORDER BY "name"`;
    const { rows } = await run(sql, binds);
    res.json(rows);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * Vehicle locations for mapping
 * Query params:
 *  - limit: number of rows (default 500, max 5000)
 *  - bbox: minLat,minLon,maxLat,maxLon (optional) or separate minLat, minLon, maxLat, maxLon params
 */
app.get("/api/vehicles/locations", async (req, res) => {
  try {
    const limit = Math.min(parseInt(req.query.limit || "500", 10), 5000);

    let minLat, minLon, maxLat, maxLon;
    if (typeof req.query.bbox === "string" && req.query.bbox.includes(",")) {
      const parts = req.query.bbox.split(",").map((v) => Number(v.trim()));
      if (parts.length === 4 && parts.every((n) => Number.isFinite(n))) {
        [minLat, minLon, maxLat, maxLon] = parts;
      }
    } else {
      minLat = Number(req.query.minLat);
      minLon = Number(req.query.minLon);
      maxLat = Number(req.query.maxLat);
      maxLon = Number(req.query.maxLon);
      if (![minLat, minLon, maxLat, maxLon].every((n) => Number.isFinite(n))) {
        minLat = minLon = maxLat = maxLon = undefined;
      }
    }

    let where = "WHERE location_lat IS NOT NULL AND location_lon IS NOT NULL";
    const binds = { lim: limit };
    if ([minLat, minLon, maxLat, maxLon].every((n) => typeof n === "number")) {
      where += " AND location_lat BETWEEN :minLat AND :maxLat AND location_lon BETWEEN :minLon AND :maxLon";
      Object.assign(binds, { minLat, maxLat, minLon, maxLon });
    }

    const sql = `
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, trim, year,
             location_lat, location_lon
      FROM vehicles
      ${where}
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(sql, binds);
    res.json(rows);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * Similar vehicles by vehicle_id (uses the vehicle's own embedding)
 * Query: limit (default 10, max 100)
 */
app.get("/api/vehicles/:id/similar", async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: "Invalid id" });
    const limit = Math.min(parseInt(req.query.limit || "10", 10), 100);

    const sql = `
      SELECT /* LLM in use is claude-sonnet-4 */
             v.vehicle_id, v.make, v.model, v.trim, v.market_price,
             VECTOR_DISTANCE(v.embedding, (SELECT embedding FROM vehicles WHERE vehicle_id = :id)) AS sim
      FROM vehicles v
      WHERE v.vehicle_id != :id
      ORDER BY sim
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(sql, { id, lim: limit });
    res.json(rows);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * Natural language vehicle similarity search.
 * Query params:
 *  - q: natural language prompt (required)
 *  - limit: max rows (default 5, max 100)
 *  - thr: similarity threshold in [0,1] (default 0.7). sim = 1/(1+distance)
 * If prompt contains brand/model tokens (e.g. "KIA SPORTAGE"), we hard-filter on MAKE/MODEL.
 * Prefers 1536-dim (vec_1536) when available; falls back to 8-dim 'embedding' otherwise.
 */
app.get("/api/vehicles/search", async (req, res) => {
  try {
    const q = (req.query.q || "").trim();
    const limit = Math.min(parseInt(req.query.limit || "5", 10), 100);
    const thr = Math.max(0, Math.min(1, Number(req.query.thr || "0.7")));
    if (!q) return res.status(400).json({ error: "q is required" });

    // Simple token extraction for brand/model filtering
    const up = q.toUpperCase();
    const words = up.split(/[^A-Z0-9\-]+/).filter(Boolean);
    const KNOWN_MAKES = new Set([
      "TOYOTA","HONDA","FORD","TESLA","NISSAN","KIA","HYUNDAI","CHEVROLET","MERCEDES","BMW","AUDI",
      "VOLKSWAGEN","VW","JEEP","DODGE","RAM","GMC","SUBARU","MAZDA","VOLVO","LEXUS","INFINITI","ACURA",
      "CADILLAC","BUICK","CHRYSLER","KIA" // keep KIA explicit
    ]);
    let mk = null;
    let mdl = null;
    for (const w of words) {
      if (!mk && KNOWN_MAKES.has(w)) mk = w === "VW" ? "VOLKSWAGEN" : w;
    }
    // Heuristic: first non-make token of length >= 2 that isn't a stop word becomes model token
    const STOP = new Set([
      "HYBRID","EV","SUV","SEDAN","TRUCK","CAR",
      "WITH","AND","OR","GOOD","GREAT","ADVANCED","SAFETY","AFFORDABLE","LUXURY",
      "LEATHER","ADAPTIVE","CRUISE","RECENTLY","SERVICED","PACKAGE","PLUS","FEATURES"
    ]);
    for (const w of words) {
      if (w === mk) continue;
      if (!STOP.has(w) && w.length >= 2) { mdl = w; break; }
    }
    // If no make was identified, avoid adding a model filter derived from generic adjectives
    if (!mk) { mdl = null; }

    // If the query exactly matches a saved description, return that vehicle immediately
    const exactSql = `
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, trim, market_price, msrp, year,
             1.0 AS sim
      FROM vehicles
      WHERE description IS NOT NULL
        AND DBMS_LOB.COMPARE(description, TO_CLOB(:d)) = 0
      FETCH FIRST 1 ROWS ONLY`;
    const ex = await run(exactSql, { d: q });
    if (ex.rows && ex.rows.length > 0) {
      return res.json(ex.rows);
    }

    const vec1536 = await embedText1536(q); // returns 1536-dim vector (fallback when no API key)
    const bindsBase = { lim: limit, thr };

    if (vec1536) {
      // Prefer description vectors if present
      let whereD = "WHERE desc_vec_1536 IS NOT NULL";
      const bindsD = { ...bindsBase, vec: vec1536 };
      if (mk) { whereD += " AND UPPER(make) = :mk"; bindsD.mk = mk; }
      if (mdl) { whereD += " AND UPPER(model) LIKE :mdl"; bindsD.mdl = mdl + "%"; }
      const sqlD = `
        SELECT /* LLM in use is claude-sonnet-4 */
               vehicle_id, make, model, trim, market_price, msrp, year,
               1/(1+VECTOR_DISTANCE(desc_vec_1536, TO_VECTOR(:vec))) AS sim
        FROM vehicles
        ${whereD}
          AND 1/(1+VECTOR_DISTANCE(desc_vec_1536, TO_VECTOR(:vec))) >= :thr
        ORDER BY sim DESC
        FETCH FIRST :lim ROWS ONLY`;
      const { rows: drows } = await run(sqlD, bindsD);
      if (drows && drows.length > 0) {
        return res.json(drows);
      }

      // Fallback to vehicle-level 1536 vector if present
      let where = "WHERE vec_1536 IS NOT NULL";
      const binds = { ...bindsBase, vec: vec1536 };
      if (mk) { where += " AND UPPER(make) = :mk"; binds.mk = mk; }
      if (mdl) { where += " AND UPPER(model) LIKE :mdl"; binds.mdl = mdl + "%"; }
      const sql1536 = `
        SELECT /* LLM in use is claude-sonnet-4 */
               vehicle_id, make, model, trim, market_price, msrp, year,
               1/(1+VECTOR_DISTANCE(vec_1536, TO_VECTOR(:vec))) AS sim
        FROM vehicles
        ${where}
          AND 1/(1+VECTOR_DISTANCE(vec_1536, TO_VECTOR(:vec))) >= :thr
        ORDER BY sim DESC
        FETCH FIRST :lim ROWS ONLY`;
      const { rows } = await run(sql1536, binds);
      if (rows && rows.length > 0) {
        return res.json(rows);
      }
      // If nothing returned (e.g., not indexed), fall through to 8-dim
    }

    // Fallback path using 8-dim 'embedding' column with the same threshold+filters
    const vec8 = noteToVector(q);
    let where8 = "WHERE embedding IS NOT NULL";
    const binds8 = { ...bindsBase, vec: vec8 };
    if (mk) { where8 += " AND UPPER(make) = :mk"; binds8.mk = mk; }
    if (mdl) { where8 += " AND UPPER(model) LIKE :mdl"; binds8.mdl = mdl + "%"; }

    const sql8 = `
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, trim, market_price, msrp, year,
             1/(1+VECTOR_DISTANCE(embedding, TO_VECTOR(:vec))) AS sim
      FROM vehicles
      ${where8}
        AND 1/(1+VECTOR_DISTANCE(embedding, TO_VECTOR(:vec))) >= :thr
      ORDER BY sim DESC
      FETCH FIRST :lim ROWS ONLY`;
    const { rows: rows8 } = await run(sql8, binds8);
    return res.json(rows8);
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * Optional: backfill 1536-dim embeddings for vehicles.
 * Body JSON: { limit?: number } (default 200)
 * Builds a concise text per vehicle and stores vec_1536 using OpenAI embeddings.
 */
app.get("/api/graph/customers", async (req, res) => {
  try {
    const limit = Math.min(Math.max(parseInt(String(req.query.limit || "200"), 10), 1), 2000);
    const sql = `
      SELECT /* LLM in use is claude-sonnet-4 */
             c.customer_id, c.name AS customer_name, c.city, c.state,
             v.vehicle_id, v.make, v.model,
             p.lane_id,
             al.name AS lane_name,
             (SELECT x FROM TABLE(SDO_UTIL.GETVERTICES(al.geom)) WHERE ROWNUM = 1) AS lon,
             (SELECT y FROM TABLE(SDO_UTIL.GETVERTICES(al.geom)) WHERE ROWNUM = 1) AS lat
      FROM ca_purchases p
      JOIN ca_customers c ON c.customer_id = p.customer_id
      JOIN vehicles  v ON v.vehicle_id  = p.vehicle_id
      LEFT JOIN auction_lanes al ON al.lane_id = p.lane_id
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(sql, { lim: limit });

    const nodeMap = new Map();
    const links = [];

    function addNode(id, obj) {
      if (!nodeMap.has(id)) nodeMap.set(id, obj);
    }

    for (const r of rows || []) {
      const cid = `C_${r.CUSTOMER_ID}`;
      const vid = `V_${r.VEHICLE_ID}`;
      addNode(cid, {
        id: cid,
        type: "customer",
        label: r.CUSTOMER_NAME,
        city: r.CITY,
        state: r.STATE
      });
      addNode(vid, {
        id: vid,
        type: "vehicle",
        label: `${r.MAKE} ${r.MODEL}`,
        vehicle_id: r.VEHICLE_ID
      });
      links.push({ source: cid, target: vid, type: "purchased" });

      if (r.LANE_ID != null) {
        const lid = `L_${r.LANE_ID}`;
        addNode(lid, {
          id: lid,
          type: "location",
          label: r.LANE_NAME,
          lane_id: r.LANE_ID,
          lat: Number(r.LAT),
          lon: Number(r.LON)
        });
        links.push({ source: vid, target: lid, type: "located_at" });
      }
    }

    res.json({ nodes: Array.from(nodeMap.values()), links });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/vehicles/vec1536/reindex", async (req, res) => {
  try {
    const limit = Math.min(Math.max(Number(req.body?.limit || 200), 1), 5000);
    const sel = `
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, NVL(trim,'') AS trim, NVL(year,0) AS year,
             TO_CHAR(market_price) AS market_price,
             TO_CHAR(msrp) AS msrp
      FROM vehicles
      WHERE vec_1536 IS NULL
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(sel, { lim: limit });
    let updated = 0;
    for (const r of rows) {
      const text = `${r.MAKE} ${r.MODEL} ${r.TRIM} ${r.YEAR} MSRP ${r.MSRP || ""} PRICE ${r.MARKET_PRICE || ""}`.trim();
      const v = await embedText1536(text);
      if (v) {
        const up = `
          UPDATE vehicles
             SET vec_1536 = TO_VECTOR(:vec)
           WHERE vehicle_id = :id`;
        await run(up, { vec: v, id: r.VEHICLE_ID });
        updated++;
      }
    }
    res.json({ ok: true, indexed: updated });
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * Populate vehicles.description and desc_vec_1536 using OpenAI embeddings.
 * Body JSON: { limit?: number } (default 500)
 */
app.post("/api/vehicles/description/reindex", async (req, res) => {
  try {
    const limit = Math.min(Math.max(Number(req.body?.limit || 500), 1), 10000);
    const sel = `
      SELECT /* LLM in use is claude-sonnet-4 */
             vehicle_id, make, model, NVL(trim,'') AS trim, NVL(year,0) AS year,
             market_price, msrp
      FROM vehicles
      WHERE desc_vec_1536 IS NULL OR description IS NULL
      FETCH FIRST :lim ROWS ONLY`;
    const { rows } = await run(sel, { lim: limit });

    let updated = 0;
    for (const r of rows) {
      const text = buildVehicleDescription(r);
      const v = await embedText1536(text);
      if (v) {
        const up = `
          UPDATE vehicles
             SET description   = :p_desc,
                 desc_vec_1536 = TO_VECTOR(:p_vec)
           WHERE vehicle_id = :p_id`;
        await run(up, { p_desc: text, p_vec: v, p_id: r.VEHICLE_ID });
        updated++;
      }
    }
    res.json({ ok: true, updated });
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * Get current vehicle description
 */
app.get("/api/vehicles/:id/description", async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: "Invalid id" });
    const q = `
      SELECT /* LLM in use is claude-sonnet-4 */
             description
      FROM vehicles
      WHERE vehicle_id = :id`;
    const { rows } = await run(q, { id });
    if (!rows || rows.length === 0) return res.status(404).json({ error: "Not found" });
    res.json({ vehicle_id: id, description: rows[0].DESCRIPTION });
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

/**
 * Update vehicle description and refresh 1536-dim description embedding
 * Body JSON: { text: string }
 */
app.put("/api/vehicles/:id/description", async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ error: "Invalid id" });
    const text = (req.body?.text || "").trim();
    if (!text) return res.status(400).json({ error: "text is required" });

    const v = await embedText1536(text);
    const up = `
      UPDATE vehicles
         SET description   = :p_desc,
             desc_vec_1536 = TO_VECTOR(:p_vec)
       WHERE vehicle_id    = :p_id`;
    await run(up, { p_desc: text, p_vec: v, p_id: id });
    res.json({ ok: true, vehicle_id: id });
  } catch (err) {
    console.error(err); res.status(500).json({ error: err.message });
  }
});

app.listen(PORT, () => {
  console.log("CoxAuto demo API listening on http://localhost:" + PORT);
});
// force restart after EZCONNECT switch
// force restart after removing WALLET_ZIP
// restart add walletLocation back
